export const PERMISSIONS = [
  {
    code: 'ropa.create',
    module: 'ropa',
    action: 'create',
    descriptionTh: 'สร้างรายการ ROPA ใหม่',
    descriptionEn: 'Create new ROPA records',
    descriptionZh: '创建新的ROPA记录',
  },
  {
    code: 'ropa.read_own',
    module: 'ropa',
    action: 'read_own',
    descriptionTh: 'ดูรายการ ROPA ของหน่วยงานตนเอง',
    descriptionEn: 'View ROPA records within own department',
    descriptionZh: '查看本部门的ROPA记录',
  },
  {
    code: 'ropa.read_all',
    module: 'ropa',
    action: 'read_all',
    descriptionTh: 'ดูรายการ ROPA ของทุกหน่วยงาน',
    descriptionEn: 'View ROPA records across all departments',
    descriptionZh: '查看所有部门的ROPA记录',
  },
  {
    code: 'ropa.update_own',
    module: 'ropa',
    action: 'update_own',
    descriptionTh: 'แก้ไขรายการ ROPA ของหน่วยงานตนเอง',
    descriptionEn: 'Edit ROPA records within own department',
    descriptionZh: '编辑本部门的ROPA记录',
  },
  {
    code: 'ropa.update_all',
    module: 'ropa',
    action: 'update_all',
    descriptionTh: 'แก้ไขรายการ ROPA ของทุกหน่วยงาน',
    descriptionEn: 'Edit ROPA records across all departments',
    descriptionZh: '编辑所有部门的ROPA记录',
  },
  {
    code: 'ropa.delete',
    module: 'ropa',
    action: 'delete',
    descriptionTh: 'ลบรายการ ROPA',
    descriptionEn: 'Delete ROPA records',
    descriptionZh: '删除ROPA记录',
  },
  {
    code: 'ropa.submit',
    module: 'ropa',
    action: 'submit',
    descriptionTh: 'ส่งรายการ ROPA เพื่อขออนุมัติ',
    descriptionEn: 'Submit ROPA records for approval',
    descriptionZh: '提交ROPA记录以供审批',
  },
  {
    code: 'ropa.approve',
    module: 'ropa',
    action: 'approve',
    descriptionTh: 'อนุมัติ/ตีกลับรายการ ROPA',
    descriptionEn: 'Approve or reject ROPA records',
    descriptionZh: '批准或拒绝ROPA记录',
  },
  {
    code: 'ropa.export',
    module: 'ropa',
    action: 'export',
    descriptionTh: 'ส่งออกรายงาน ROPA',
    descriptionEn: 'Export ROPA reports',
    descriptionZh: '导出ROPA报告',
  },
  {
    code: 'users.manage',
    module: 'users',
    action: 'manage',
    descriptionTh: 'จัดการผู้ใช้งานระบบ',
    descriptionEn: 'Manage system users',
    descriptionZh: '管理系统用户',
  },
  {
    code: 'roles.manage',
    module: 'roles',
    action: 'manage',
    descriptionTh: 'จัดการบทบาทและสิทธิ์การใช้งาน',
    descriptionEn: 'Manage roles and permission matrix',
    descriptionZh: '管理角色和权限矩阵',
  },
  {
    code: 'departments.manage',
    module: 'departments',
    action: 'manage',
    descriptionTh: 'จัดการหน่วยงาน',
    descriptionEn: 'Manage departments',
    descriptionZh: '管理部门',
  },
  {
    code: 'audit.view',
    module: 'audit',
    action: 'view',
    descriptionTh: 'ดูประวัติการใช้งานระบบ',
    descriptionEn: 'View system audit log',
    descriptionZh: '查看系统审计日志',
  },
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number]['code'];

export const DEFAULT_ROLES = [
  {
    code: 'super_admin',
    nameTh: 'ผู้ดูแลระบบสูงสุด',
    nameEn: 'Super Admin',
    nameZh: '超级管理员',
    isSystem: true,
    permissions: PERMISSIONS.map((p) => p.code) as PermissionCode[],
  },
  {
    code: 'dpo',
    nameTh: 'เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล',
    nameEn: 'DPO / Compliance Officer',
    nameZh: '数据保护官/合规官',
    isSystem: true,
    permissions: [
      'ropa.read_all',
      'ropa.update_all',
      'ropa.approve',
      'ropa.export',
      'audit.view',
    ] as PermissionCode[],
  },
  {
    code: 'dept_editor',
    nameTh: 'ผู้บันทึกข้อมูลหน่วยงาน',
    nameEn: 'Department Editor',
    nameZh: '部门编辑员',
    isSystem: true,
    permissions: [
      'ropa.create',
      'ropa.read_own',
      'ropa.update_own',
      'ropa.submit',
      'ropa.export',
    ] as PermissionCode[],
  },
  {
    code: 'viewer',
    nameTh: 'ผู้ตรวจสอบ/ผู้เยี่ยมชม',
    nameEn: 'Viewer / Auditor',
    nameZh: '查看者/审计员',
    isSystem: true,
    permissions: ['ropa.read_all', 'ropa.export', 'audit.view'] as PermissionCode[],
  },
] as const;

export const DEFAULT_DEPARTMENTS = [
  { code: 'HQ', nameTh: 'สำนักงานส่วนกลาง', nameEn: 'Head Office', nameZh: '总部' },
  { code: 'IT', nameTh: 'หน่วยงานเทคโนโลยีสารสนเทศ', nameEn: 'Information Technology', nameZh: '信息技术部' },
  { code: 'HR', nameTh: 'หน่วยงานทรัพยากรบุคคล', nameEn: 'Human Resources', nameZh: '人力资源部' },
] as const;
